baseurl = "takbo.rogermolas.com"
title = "Roger Molas"
theme = "hugo-universal-theme"
themesDir = "themes/"
publishDir = "docs"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "HOME"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "BLOGS"
    url  = "http://www.rogermolas.com/blog/"
    weight = 2

[params]
    #author = "DevCows"
    #defaultKeywords = ["devows", "hugo", "go"]
    #defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"
    email = "contact@rogermolas.com"

   # about_us = "<p>.</p>"
    copyright = "Copyright (c) 2018, Roger Molas; All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"
    
   # address = """<p><strong>Universal Ltd.</strong>
   #     <br>13/25 New Avenue
   #     <br>Newtown upon River
   #     <br>45Y 73J
   #     <br>England
   #     <br>
   #     <strong>Great Britain</strong>
   #   </p>
   #   """

[Permalinks]
   # blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact me on contact@rogermolas.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.


[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "Other freelance work and opensource libraries"
    link_url = "http://www.rogermolas.com/projects/"
    link_text = "Check projects page"
   